id = "cql"
name = "CQL"
description = "CQL support."
version = "2.0.0"
schema_version = 1
authors = ["Akzestia <akzestia@gmail.com>"]
repository = "https://github.com/Akzestia/zed-cql"

[language_servers.cql]
name = "CQL LSP"
languages = ["CQL"]

[grammars.cql]
repository = "https://github.com/Akzestia/tree-sitter-cql"
rev = "0db616ae8ac63ad232dcc264a1e0ed9c93602481"
